// Copyright (c) .NET Foundation. All rights reserved.
// Licensed under the Apache License, Version 2.0. See License.txt in the project root for license information.

using System.Collections.Generic;

namespace MusicStoreViews.Models
{
    public class MusicStoreContext
    {
        public IList<Artist> Artists { get; } = new List<Artist>
        {
            new Artist { ArtistId = 1, Name = "65daysofstatic" },
            new Artist { ArtistId = 2, Name = "R.E.M." },
            new Artist { ArtistId = 3, Name = "Queensr\u00FFche" },
            new Artist { ArtistId = 4, Name = "Queen" },
            new Artist { ArtistId = 5, Name = "Public Enemy" },
            new Artist { ArtistId = 6, Name = "PSY" },
            new Artist { ArtistId = 7, Name = "Projected" },
            new Artist { ArtistId = 8, Name = "Prince" },
            new Artist { ArtistId = 9, Name = "Portishead" },
            new Artist { ArtistId = 10, Name = "Porcupine Tree" },
            new Artist { ArtistId = 11, Name = "Plug" },
            new Artist { ArtistId = 12, Name = "Pink Floyd" },
            new Artist { ArtistId = 13, Name = "Pet Shop Boys" },
            new Artist { ArtistId = 14, Name = "Pearl Jam" },
            new Artist { ArtistId = 15, Name = "Paul Van Dyk" },
            new Artist { ArtistId = 16, Name = "Paul Oakenfold" },
            new Artist { ArtistId = 17, Name = "Radiohead" },
            new Artist { ArtistId = 18, Name = "Paul D'Ianno" },
            new Artist { ArtistId = 19, Name = "Rancid" },
            new Artist { ArtistId = 20, Name = "Raunchy" },
            new Artist { ArtistId = 21, Name = "Sheryl Crow" },
            new Artist { ArtistId = 22, Name = "Sergei Prokofiev & Yuri Temirkanov" },
            new Artist { ArtistId = 23, Name = "Scorpions" },
            new Artist { ArtistId = 24, Name = "Scholars Baroque Ensemble" },
            new Artist { ArtistId = 25, Name = "Sasha" },
            new Artist { ArtistId = 26, Name = "Sarah Brightman" },
            new Artist { ArtistId = 27, Name = "Sara Tavares" },
            new Artist { ArtistId = 28, Name = "Santana" },
            new Artist { ArtistId = 29, Name = "Rush" },
            new Artist { ArtistId = 30, Name = "Run DMC" },
            new Artist { ArtistId = 31, Name = "Royal Philharmonic Orchestra" },
            new Artist { ArtistId = 32, Name = "London Classical Players" },
            new Artist { ArtistId = 33, Name = "Robert James" },
            new Artist { ArtistId = 34, Name = "Rick Ross" },
            new Artist { ArtistId = 35, Name = "Red Hot Chili Peppers" },
            new Artist { ArtistId = 36, Name = "Raul Seixas" },
            new Artist { ArtistId = 37, Name = "Sir Georg Solti & Wiener Philharmoniker" },
            new Artist { ArtistId = 38, Name = "Papa Wemba" },
            new Artist { ArtistId = 39, Name = "Paddy Casey" },
            new Artist { ArtistId = 40, Name = "M\u00F6tley Cr\u00FCe" },
            new Artist { ArtistId = 41, Name = "Modest Mouse" },
            new Artist { ArtistId = 42, Name = "Mobile" },
            new Artist { ArtistId = 43, Name = "Milton Nascimento" },
            new Artist { ArtistId = 44, Name = "Miles Davis" },
            new Artist { ArtistId = 45, Name = "Michael Tilson Thomas" },
            new Artist { ArtistId = 46, Name = "Michael Bolton" },
            new Artist { ArtistId = 47, Name = "M-Flo" },
            new Artist { ArtistId = 48, Name = "Metallica" },
            new Artist { ArtistId = 49, Name = "Men At Work" },
            new Artist { ArtistId = 50, Name = "Melanie Fiona" },
            new Artist { ArtistId = 51, Name = "Mela Tenenbaum, Pro Musica Prague & Richard Kapp" },
            new Artist { ArtistId = 52, Name = "Megadeth" },
            new Artist { ArtistId = 53, Name = "Maurizio Pollini" },
            new Artist { ArtistId = 54, Name = "Massive Attack" },
            new Artist { ArtistId = 55, Name = "Mot\u00F6rhead" },
            new Artist { ArtistId = 56, Name = "Page & Plant" },
            new Artist { ArtistId = 57, Name = "Mumford & Sons" },
            new Artist { ArtistId = 58, Name = "Nash Ensemble" },
            new Artist { ArtistId = 59, Name = "Ozzy Osbourne" },
            new Artist { ArtistId = 60, Name = "Os Paralamas Do Sucesso" },
            new Artist { ArtistId = 61, Name = "Orchestra of The Age of Enlightenment" },
            new Artist { ArtistId = 62, Name = "Opeth" },
            new Artist { ArtistId = 63, Name = "Olodum" },
            new Artist { ArtistId = 64, Name = "Oasis" },
            new Artist { ArtistId = 65, Name = "O Ter\u00E7o" },
            new Artist { ArtistId = 66, Name = "Nujabes" },
            new Artist { ArtistId = 67, Name = "Norah Jones" },
            new Artist { ArtistId = 68, Name = "Nirvana" },
            new Artist { ArtistId = 69, Name = "Nine Inch Nails" },
            new Artist { ArtistId = 70, Name = "Nicolaus Esterhazy Sinfonia" },
            new Artist { ArtistId = 71, Name = "Nick Cave and the Bad Seeds" },
            new Artist { ArtistId = 72, Name = "New York Dolls" },
            new Artist { ArtistId = 73, Name = "Neil Young" },
            new Artist { ArtistId = 74, Name = "Munkle" },
            new Artist { ArtistId = 75, Name = "Martin Roscoe" },
            new Artist { ArtistId = 76, Name = "Skank" },
            new Artist { ArtistId = 77, Name = "Slash" },
            new Artist { ArtistId = 78, Name = "Trampled By Turtles" },
            new Artist { ArtistId = 79, Name = "Tori Amos" },
            new Artist { ArtistId = 80, Name = "Tool" },
            new Artist { ArtistId = 81, Name = "Ton Koopman" },
            new Artist { ArtistId = 82, Name = "Tim Maia" },
            new Artist { ArtistId = 83, Name = "Ti\u00EBsto" },
            new Artist { ArtistId = 84, Name = "Thievery Corporation" },
            new Artist { ArtistId = 85, Name = "TheStart" },
            new Artist { ArtistId = 86, Name = "Them Crooked Vultures" },
            new Artist { ArtistId = 87, Name = "The Who" },
            new Artist { ArtistId = 88, Name = "The Stone Roses" },
            new Artist { ArtistId = 89, Name = "The Smashing Pumpkins" },
            new Artist { ArtistId = 90, Name = "The Rubberbandits" },
            new Artist { ArtistId = 91, Name = "The Rolling Stones" },
            new Artist { ArtistId = 92, Name = "The Prodigy" },
            new Artist { ArtistId = 93, Name = "Trans-Siberian Orchestra" },
            new Artist { ArtistId = 94, Name = "The Posies" },
            new Artist { ArtistId = 95, Name = "Tygers of Pan Tang" },
            new Artist { ArtistId = 96, Name = "UB40" },
            new Artist { ArtistId = 97, Name = "Yo-Yo Ma" },
            new Artist { ArtistId = 98, Name = "Yes" },
            new Artist { ArtistId = 99, Name = "Yehudi Menuhin" },
            new Artist { ArtistId = 100, Name = "Yano" },
            new Artist { ArtistId = 101, Name = "Wilhelm Kempff" },
            new Artist { ArtistId = 102, Name = "Wendy Carlos" },
            new Artist { ArtistId = 103, Name = "Weird Al" },
            new Artist { ArtistId = 104, Name = "Weezer" },
            new Artist { ArtistId = 105, Name = "Vin\u00EDcius De Moraes" },
            new Artist { ArtistId = 106, Name = "Vicente Fernandez" },
            new Artist { ArtistId = 107, Name = "Venus Hum" },
            new Artist { ArtistId = 108, Name = "Velvet Revolver" },
            new Artist { ArtistId = 109, Name = "Various Artists" },
            new Artist { ArtistId = 110, Name = "Van Halen" },
            new Artist { ArtistId = 111, Name = "Uh Huh Her " },
            new Artist { ArtistId = 112, Name = "U2" },
            new Artist { ArtistId = 113, Name = "Skrillex" },
            new Artist { ArtistId = 114, Name = "The Police" },
            new Artist { ArtistId = 115, Name = "The Lumineers" },
            new Artist { ArtistId = 116, Name = "Tears For Fears" },
            new Artist { ArtistId = 117, Name = "Talking Heads" },
            new Artist { ArtistId = 118, Name = "T&N" },
            new Artist { ArtistId = 119, Name = "System Of A Down" },
            new Artist { ArtistId = 120, Name = "Supreme Beings of Leisure" },
            new Artist { ArtistId = 121, Name = "Sufjan Stevens" },
            new Artist { ArtistId = 122, Name = "Styx" },
            new Artist { ArtistId = 123, Name = "Stone Temple Pilots" },
            new Artist { ArtistId = 124, Name = "Sting" },
            new Artist { ArtistId = 125, Name = "Stevie Ray Vaughan" },
            new Artist { ArtistId = 126, Name = "Stevie Ray Vaughan & Double Trouble" },
            new Artist { ArtistId = 127, Name = "Spyro Gyra" },
            new Artist { ArtistId = 128, Name = "Soundgarden" },
            new Artist { ArtistId = 129, Name = "Soul-Junk" },
            new Artist { ArtistId = 130, Name = "Slayer" },
            new Artist { ArtistId = 131, Name = "Ted Nugent" },
            new Artist { ArtistId = 132, Name = "The Offspring" },
            new Artist { ArtistId = 133, Name = "Temple of the Dog" },
            new Artist { ArtistId = 134, Name = "The 12 Cellists of The Berlin Philharmonic" },
            new Artist { ArtistId = 135, Name = "The King's Singers" },
            new Artist { ArtistId = 136, Name = "The Jezabels" },
            new Artist { ArtistId = 137, Name = "The Head and the Heart" },
            new Artist { ArtistId = 138, Name = "The Go! Team" },
            new Artist { ArtistId = 139, Name = "The Eagles of Death Metal" },
            new Artist { ArtistId = 140, Name = "The Doors" },
            new Artist { ArtistId = 141, Name = "The Decemberists" },
            new Artist { ArtistId = 142, Name = "The Cure" },
            new Artist { ArtistId = 143, Name = "The Cult" },
            new Artist { ArtistId = 144, Name = "The Cat Empire" },
            new Artist { ArtistId = 145, Name = "The Carpenters" },
            new Artist { ArtistId = 146, Name = "The Black Keys" },
            new Artist { ArtistId = 147, Name = "The Black Crowes" },
            new Artist { ArtistId = 148, Name = "The Beatles" },
            new Artist { ArtistId = 149, Name = "The Axis of Awesome" },
            new Artist { ArtistId = 150, Name = "Terry Bozzio, Tony Levin & Steve Stevens" },
            new Artist { ArtistId = 151, Name = "Zeca Pagodinho" },
            new Artist { ArtistId = 152, Name = "Mark Knopfler" },
            new Artist { ArtistId = 153, Name = "Marillion" },
            new Artist { ArtistId = 154, Name = "Chicago " },
            new Artist { ArtistId = 155, Name = "Chic" },
            new Artist { ArtistId = 156, Name = "Cayouche" },
            new Artist { ArtistId = 157, Name = "C\u00E1ssia Eller" },
            new Artist { ArtistId = 158, Name = "Carreras, Pavarotti, Domingo" },
            new Artist { ArtistId = 159, Name = "Carly Rae Jepsen" },
            new Artist { ArtistId = 160, Name = "Calexico" },
            new Artist { ArtistId = 161, Name = "Cake" },
            new Artist { ArtistId = 162, Name = "Caetano Veloso" },
            new Artist { ArtistId = 163, Name = "Butch Walker & The Black Widows" },
            new Artist { ArtistId = 164, Name = "Burial" },
            new Artist { ArtistId = 165, Name = "Buddy Guy" },
            new Artist { ArtistId = 166, Name = "Bruce Dickinson" },
            new Artist { ArtistId = 167, Name = "Britten Sinfonia, Ivor Bolton & Lesley Garrett" },
            new Artist { ArtistId = 168, Name = "Boston Symphony Orchestra & Seiji Ozawa" },
            new Artist { ArtistId = 169, Name = "Chicago Symphony Orchestra & Fritz Reiner" },
            new Artist { ArtistId = 170, Name = "Blues Traveler" },
            new Artist { ArtistId = 171, Name = "Chico Buarque" },
            new Artist { ArtistId = 172, Name = "Choir Of Westminster Abbey & Simon Preston" },
            new Artist { ArtistId = 173, Name = "Def Leppard" },
            new Artist { ArtistId = 174, Name = "Deep Purple" },
            new Artist { ArtistId = 175, Name = "deadmau5" },
            new Artist { ArtistId = 176, Name = "David Guetta" },
            new Artist { ArtistId = 177, Name = "David Coverdale" },
            new Artist { ArtistId = 178, Name = "David Bowie" },
            new Artist { ArtistId = 179, Name = "Danielson Famile" },
            new Artist { ArtistId = 180, Name = "Daft Punk" },
            new Artist { ArtistId = 181, Name = "Crosby, Stills, Nash, and Young" },
            new Artist { ArtistId = 182, Name = "Creedence Clearwater Revival" },
            new Artist { ArtistId = 183, Name = "Coldplay" },
            new Artist { ArtistId = 184, Name = "Cl\u00E1udio Zoli" },
            new Artist { ArtistId = 185, Name = "Cidade Negra" },
            new Artist { ArtistId = 186, Name = "Christopher O'Riley" },
            new Artist { ArtistId = 187, Name = "Chris Cornell" },
            new Artist { ArtistId = 188, Name = "Chico Science & Na\u00E7\u00E3o Zumbi" },
            new Artist { ArtistId = 189, Name = "Deftones" },
            new Artist { ArtistId = 190, Name = "BL\u00D8F" },
            new Artist { ArtistId = 191, Name = "Black Label Society" },
            new Artist { ArtistId = 192, Name = "Alison Krauss" },
            new Artist { ArtistId = 193, Name = "Alice in Chains" },
            new Artist { ArtistId = 194, Name = "Alberto Turco & Nova Schola Gregoriana" },
            new Artist { ArtistId = 195, Name = "Alanis Morissette" },
            new Artist { ArtistId = 196, Name = "Alabama Shakes" },
            new Artist { ArtistId = 197, Name = "Al di Meola" },
            new Artist { ArtistId = 198, Name = "Aisha Duo" },
            new Artist { ArtistId = 199, Name = "Aerosmith" },
            new Artist { ArtistId = 200, Name = "Adrian Leaper & Doreen de Feis" },
            new Artist { ArtistId = 201, Name = "Adicts" },
            new Artist { ArtistId = 202, Name = "Accept" },
            new Artist { ArtistId = 203, Name = "AC/DC" },
            new Artist { ArtistId = 204, Name = "Above the Fold" },
            new Artist { ArtistId = 205, Name = "Above & Beyond" },
            new Artist { ArtistId = 206, Name = "Aaron Goldberg" },
            new Artist { ArtistId = 207, Name = "Amon Amarth" },
            new Artist { ArtistId = 208, Name = "Black Sabbath" },
            new Artist { ArtistId = 209, Name = "Amon Tobin" },
            new Artist { ArtistId = 210, Name = "Amy Winehouse" },
            new Artist { ArtistId = 211, Name = "Billy Cobham" },
            new Artist { ArtistId = 212, Name = "Berliner Philharmoniker" },
            new Artist { ArtistId = 213, Name = "Before the Dawn" },
            new Artist { ArtistId = 214, Name = "Bee Gees" },
            new Artist { ArtistId = 215, Name = "BBC Concert Orchestra" },
            new Artist { ArtistId = 216, Name = "Barenaked Ladies" },
            new Artist { ArtistId = 217, Name = "Bad Religion" },
            new Artist { ArtistId = 218, Name = "Audioslave" },
            new Artist { ArtistId = 219, Name = "Arcade Fire" },
            new Artist { ArtistId = 220, Name = "Armand Van Helden" },
            new Artist { ArtistId = 221, Name = "Aqua" },
            new Artist { ArtistId = 222, Name = "Apocalyptica" },
            new Artist { ArtistId = 223, Name = "Ant\u00F4nio Carlos Jobim" },
            new Artist { ArtistId = 224, Name = "Anthrax" },
            new Artist { ArtistId = 225, Name = "Anita Ward" },
            new Artist { ArtistId = 226, Name = "Amr Diab" },
            new Artist { ArtistId = 227, Name = "Marisa Monte" },
            new Artist { ArtistId = 228, Name = "Dennis Chambers" },
            new Artist { ArtistId = 229, Name = "Dio" },
            new Artist { ArtistId = 230, Name = "Justice" },
            new Artist { ArtistId = 231, Name = "Julian Bream" },
            new Artist { ArtistId = 232, Name = "Judas Priest" },
            new Artist { ArtistId = 233, Name = "Journey" },
            new Artist { ArtistId = 234, Name = "Jota Quest" },
            new Artist { ArtistId = 235, Name = "Jorge Ben" },
            new Artist { ArtistId = 236, Name = "John Mayer" },
            new Artist { ArtistId = 237, Name = "John Digweed" },
            new Artist { ArtistId = 238, Name = "Joe Satriani" },
            new Artist { ArtistId = 239, Name = "Jimmy Smith" },
            new Artist { ArtistId = 240, Name = "Jimmy Buffett" },
            new Artist { ArtistId = 241, Name = "Jimi Hendrix" },
            new Artist { ArtistId = 242, Name = "Jamiroquai" },
            new Artist { ArtistId = 243, Name = "James Levine" },
            new Artist { ArtistId = 244, Name = "Jagjit Singh" },
            new Artist { ArtistId = 245, Name = "Orchestre de l'Op\u00E9ra de Lyon" },
            new Artist { ArtistId = 246, Name = "Iron Maiden" },
            new Artist { ArtistId = 247, Name = "King Crimson" },
            new Artist { ArtistId = 248, Name = "LCD Soundsystem" },
            new Artist { ArtistId = 249, Name = "Marcos Valle" },
            new Artist { ArtistId = 250, Name = "Lura" },
            new Artist { ArtistId = 251, Name = "Lulu Santos" },
            new Artist { ArtistId = 252, Name = "Luciana Souza/Romero Lubambo" },
            new Artist { ArtistId = 253, Name = "Los Tigres del Norte" },
            new Artist { ArtistId = 254, Name = "London Symphony Orchestra" },
            new Artist { ArtistId = 255, Name = "Lokua Kanza" },
            new Artist { ArtistId = 256, Name = "Live" },
            new Artist { ArtistId = 257, Name = "Linkin Park" },
            new Artist { ArtistId = 258, Name = "Limp Bizkit" },
            new Artist { ArtistId = 259, Name = "Les Arts Florissants & William Christie" },
            new Artist { ArtistId = 260, Name = "Lenny Kravitz" },
            new Artist { ArtistId = 261, Name = "Legi\u00E3o Urbana" },
            new Artist { ArtistId = 262, Name = "Led Zeppelin" },
            new Artist { ArtistId = 263, Name = "Le Tigre" },
            new Artist { ArtistId = 264, Name = "Kiss" },
            new Artist { ArtistId = 265, Name = "Deva Premal" },
            new Artist { ArtistId = 266, Name = "INXS" },
            new Artist { ArtistId = 267, Name = "In This Moment" },
            new Artist { ArtistId = 268, Name = "Epica" },
            new Artist { ArtistId = 269, Name = "Enya" },
            new Artist { ArtistId = 270, Name = "English Concert & Trevor Pinnock" },
            new Artist { ArtistId = 271, Name = "Eminem" },
            new Artist { ArtistId = 272, Name = "Elis Regina" },
            new Artist { ArtistId = 273, Name = "Edo de Waart & San Francisco Symphony" },
            new Artist { ArtistId = 274, Name = "Ed Motta" },
            new Artist { ArtistId = 275, Name = "Earl Scruggs" },
            new Artist { ArtistId = 276, Name = "Duck Sauce" },
            new Artist { ArtistId = 277, Name = "Dream Theater" },
            new Artist { ArtistId = 278, Name = "Dread Zeppelin" },
            new Artist { ArtistId = 279, Name = "Dr. Dre" },
            new Artist { ArtistId = 280, Name = "Donna Summer" },
            new Artist { ArtistId = 281, Name = "Dolly Parton" },
            new Artist { ArtistId = 282, Name = "Djavan" },
            new Artist { ArtistId = 283, Name = "Eric B. and Rakim" },
            new Artist { ArtistId = 284, Name = "Incognito" },
            new Artist { ArtistId = 285, Name = "Eric Clapton" },
            new Artist { ArtistId = 286, Name = "Faith No More" },
            new Artist { ArtistId = 287, Name = "Gustav Mahler" },
            new Artist { ArtistId = 288, Name = "Guns N' Roses" },
            new Artist { ArtistId = 289, Name = "G\u00F6teborgs Symfoniker & Neeme J\u00E4rvi" },
            new Artist { ArtistId = 290, Name = "Gonzaguinha" },
            new Artist { ArtistId = 291, Name = "Godsmack" },
            new Artist { ArtistId = 292, Name = "Gilberto Gil" },
            new Artist { ArtistId = 293, Name = "Gerald Moore" },
            new Artist { ArtistId = 294, Name = "Garbage" },
            new Artist { ArtistId = 295, Name = "Funk Como Le Gusta" },
            new Artist { ArtistId = 296, Name = "Fretwork" },
            new Artist { ArtistId = 297, Name = "Frank Zappa & Captain Beefheart" },
            new Artist { ArtistId = 298, Name = "Four Tet" },
            new Artist { ArtistId = 299, Name = "Foo Fighters" },
            new Artist { ArtistId = 300, Name = "Filter" },
            new Artist { ArtistId = 301, Name = "Falamansa" },
            new Artist { ArtistId = 302, Name = "Eugene Ormandy" },
            new Artist { ArtistId = 303, Name = "\u05D0\u05E8\u05D9\u05E7 \u05D0\u05D9\u05E0\u05E9\u05D8\u05D9\u05D9\u05DF" },
        };

        public IList<Genre> Genres { get; } = new List<Genre>
        {
            new Genre { GenreId = 0, Name = "Pop"  },
            new Genre { GenreId = 1, Name = "Rock"  },
            new Genre { GenreId = 2, Name = "Jazz"  },
            new Genre { GenreId = 3, Name = "Metal"  },
            new Genre { GenreId = 4, Name = "Electronic"  },
            new Genre { GenreId = 5, Name = "Blues"  },
            new Genre { GenreId = 6, Name = "Latin"  },
            new Genre { GenreId = 7, Name = "Rap"  },
            new Genre { GenreId = 8, Name = "Classical"  },
            new Genre { GenreId = 9, Name = "Alternative"  },
            new Genre { GenreId = 10, Name = "Country"  },
            new Genre { GenreId = 11, Name = "Punk"  },
        };

        public IList<CartItem> CartItems { get; } = new List<CartItem>();
    }
}